apiVersion: backstage.io/v1alpha1
kind: Resource
metadata:
  name: sube8uc5x-go-gitops
  description: This is GitOps manifest for sube8uc5x-go   
  links:
    - url: https://www.redhat.com/en/solutions/trusted-software-supply-chain
      title: Trusted Secure Supply Chain 
      icon: dashboard
      type: admin-dashboard
  annotations:    
    argocd/app-selector: rhtap/gitops=sube8uc5x-go
    backstage.io/kubernetes-id: sube8uc5x-go 
    backstage.io/techdocs-ref: dir:. 
    janus-idp.io/tekton: sube8uc5x-go   
spec:
  type: gitops
  owner: user:guest 
  lifecycle: experimental
  dependsOn:
    - component:sube8uc5x-go
